// Generated by CoffeeScript 1.6.3
(function() {
  var autoLink,
    __slice = [].slice;

  autoLink = function() {
    var k, linkAttributes, option, options, pattern, v;
    var activeUrl = parse_url(document.URL);
    
    options = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    
    
    
    pattern = /(^|\s)((?:https?|ftp):\/\/[\-A-Z0-9+\u0026@#\/%?=()~_|!:,.;]*[\-A-Z0-9+\u0026@#\/%=~()_|])/gi;
   
    
    
    if (!(options.length > 0)) {
      options[0] = {target:'auto'};
    }
    
    option = options[0];
    
    
    
    linkAttributes = ((function() {
      var _results;
      _results = [];
      for (k in option) {
        v = option[k];
        if (k !== 'callback') {
          _results.push(' ' + k + '="' + v + '"');
        }
      }
      return _results;
    })()).join('');
    
    return this.replace(pattern, function(match, space, url) {
      var link;
      
      	pUrl = parse_url(url);
      	
      	if(pUrl.host != activeUrl.host)
      	{
      		linkAttributes = linkAttributes.replace(' target="auto"',' target="_blank"');
      	}
      	else
      	{
      		linkAttributes = linkAttributes.replace(' target="auto"','');
      	}
      
      link = (typeof option.callback === "function" ? option.callback(url) : void 0) || ('<a href="' + url + '"' + linkAttributes + '>' + url.replace('http://','').replace('https://','') + '</a>');
      return "" + space + link;
    });
  };

  String.prototype['autoLink'] = autoLink;

}).call(this);
