FROM registry.gitlab.com/foodsharing-dev/images/php:2.17

COPY --chown=www-data:www-data . /app
RUN mkdir /app/vendor && mkdir /downloads && chown www-data:www-data /app/vendor /downloads
WORKDIR /app
