#!/bin/bash

set -e

source $(dirname "$0")/inc.sh

echo "Building webpack assets"
# volume is created as root-owned
run-in-container-asroot client "chown -R $UID /app/client/node_modules"
run-in-container client 'yarn && yarn build'

echo "Done"
