#!/bin/bash

echo
echo "  You don't need to use this command any more!"
echo
echo "  The hot reloading webpack stuff is now integrated into the main setup"
echo
echo "  Just visit http://localhost:18080 and all should work :)"
echo
echo "    ... assuming you already ran ./scripts/start"
echo
