#!/bin/bash
# run docker-compose with the container specified by $FS_ENV and a suitable project name
# which command to run by docker-compose and additional arguments is specified by the arguments
# of this script

set -o errexit

dir=$(dirname "$0")

# Export the current host operating system to FS_PLATFORM
unameOut="$(uname -s)"
case "${unameOut}" in
    Darwin*)    export FS_PLATFORM=mac;;
    *)          export FS_PLATFORM=default;;
esac

# shellcheck source=./inc.sh
source "$dir"/inc.sh

docker-compose \
  --file "$dir"/../docker/docker-compose."$FS_ENV".yml \
  --project-name foodsharing_"$FS_ENV" \
  "$@"
