#!/bin/bash
# run docker-compose with the container specified by $FS_ENV and a suitable project name
# which command to run by docker-compose and additional arguments is specified by the arguments
# of this script

set -o errexit

dir=$(dirname "$0")

source $dir/inc.sh

docker-compose \
    -f $dir/../docker/docker-compose.yml \
  -f $dir/../docker/docker-compose.$FS_ENV.yml \
  -p foodsharing_$FS_ENV \
  "$@"
