#!/bin/bash
# run docker-compose with the container specified by $FS_ENV and a suitable project name
# which command to execute by docker-compose and additional arguments is specified by the arguments
# of this script

set -o errexit

dir=$(dirname "$0")

source $dir/inc.sh

docker-compose \
  --file $dir/../docker/docker-compose.$FS_ENV.yml \
  --project-name foodsharing_$FS_ENV \
  "$@"
