#!/bin/bash

export FS_ENV=dev

set -o errexit

dir=$(dirname "$0")

# shellcheck source=./inc.sh
source "$dir"/inc.sh

echo "Linting client js"
run-in-container client yarn lint

echo "Linting chat js"
run-in-container chat yarn lint
