#!/bin/bash

export FS_ENV=dev

set -o errexit

source $(dirname "$0")/inc.sh

echo "Linting php with parallel-lint"
run-in-container app vendor/bin/parallel-lint --exclude vendor .

echo "Linting php with phpstan"
run-in-container app vendor/bin/phpstan analyse --memory-limit=768M
