#!/bin/bash

export FS_ENV=${FS_ENV:-dev}

set -o errexit

dir=$(dirname "$0")

source $dir/inc.sh

# directories used by the application

dirs="\
  images \
  images/basket \
  images/wallpost \
  images/picture \
  images/workgroup \
  data/attach \
  data/mailattach \
  data/mailattach/tmp \
  data/pass \
  data/visite \
  cache \
  cache/searchindex \
  cache/htmlpurifier-cache \
  tmp \
"

echo "Creating directories"

exec-in-container-asroot app \
  "mkdir --parents $dirs && chmod 777 $dirs && chown --recursive www-data:www-data $dirs"

echo "Done"
