#!/bin/bash

# rebuilds just one container
# useful if you change the nginx config for example

set -o errexit

dir=$(dirname "$0")

# shellcheck source=./inc.sh
source "$dir"/inc.sh

container=${1:-web}

dc stop "$container"
dc build "$container"
dc up -d --no-deps "$container"
