#!/bin/bash

set -e

. $(dirname "$0")/inc.sh

dc kill

name=foodsharing_$FS_ENV

echo "Removing $name containers"
containers=$(docker ps -aq -f name=$name)
if [ "x" != "x$containers" ]; then
  docker rm $containers
else
  echo "... there are none!"
fi

volume_name=foodsharing$FS_ENV

echo "Removing $volume_name volumes"
volumes=$(docker volume ls -q -f name=$volume_name)
if [ "x" != "x$volumes" ]; then
  docker volume rm $volumes
else
  echo "... there are none!"
fi
