#!/bin/bash

export FS_ENV=dev

# set -o errexit tells the shell to exit as soon as a command exits with non-zero status, i.e. fails
set -o errexit

# source runs the content of the argument as if it was here (without launching a subshell!)
source $(dirname "$0")/inc.sh

exec-in-container app vendor/bin/codecept foodsharing:seed "$@"
