#!/bin/bash

export FS_ENV=dev

# set -e tells the shell to exit as a command exits with non-zero status, i.e. fails
set -e

# . is a bash builtin, synonymous to source
# it runs the content of the argument as if there were here (without launching a subshell!)
. $(dirname "$0")/inc.sh

exec-in-container app vendor/bin/codecept foodsharing:seed "$@"
