#!/bin/bash

export FS_ENV=dev

# set -e tells the shell to exit as a command exits with non-zero status, i.e. fails
set -e

. $(dirname "$0")/inc.sh

exec-in-container app vendor/bin/codecept foodsharing:seed "$@"
