#!/bin/bash

export FS_ENV=dev

# set -o errexit tells the shell to exit as soon as a command exits with non-zero status, i.e. fails
set -o errexit

dir=$(dirname "$0")

# source runs the content of the argument as if there were here (without launching a subshell!)
# inc.sh defines basic functions, mainly to run commands in containers
source $dir/inc.sh

echo "Bringing up containers"
# dc is defined in inc.sh and starts docker-compose with following arguments
# up starts the container, --detach: run in background as a deamon
dc up --detach
$dir/mkdirs

echo "Running composer install"
# exec-in-container is defined in inc.sh
exec-in-container app composer install
exec-in-container-asroot app rm -rf cache/.views-cache cache/di-cache.php

echo "Waiting for mysql"
wait-for-mysql

# Creating db
createdb foodsharing

# Migrating db
migratedb foodsharing || true

# Building assets
$dir/build-assets

echo
echo "  Go visit http://localhost:18080 now!"
echo
echo "  Or view logs with:"
echo
echo "    ./scripts/docker-compose logs -f"
echo
echo "  Or seed the db with some data:"
echo
echo "    ./scripts/seed"
echo
