#!/bin/bash

export FS_ENV=test

# does not build the environment
# assumes all the tests are idempotent
# the db does not get recreated between runs

set -e

. $(dirname "$0")/inc.sh

echo "Running tests"
exec-in-container app vendor/bin/codecept run "$@"

if [ $# -eq 0 ]; then
  echo "Running chat tests"
  run-in-container chat npm test
fi

echo "Done!"

