#!/bin/bash

export FS_ENV=test

set -o errexit

dir=$(dirname "$0")

# shellcheck source=./inc.sh
source "$dir"/inc.sh

echo "Bring up containers"
# up starts the container, -d: run in background as a deamon
dc up -d

"$dir"/mkdirs

echo "Waiting for database to start"
wait-for-mysql

echo "Flush redis"
exec-in-container redis redis-cli flushall

echo "Initializing database"
sql-query mysql 'drop database if exists foodsharing; create database foodsharing'

echo "Running migrations"
migratedb foodsharing

echo "Running composer install"
exec-in-container app 'composer install'

echo "Running tests"
exec-in-container selenium "find /home/seluser/Downloads -type f -print0 | xargs -r -n 1 -0 rm"
exec-in-container-asroot app rm --recursive --force cache/.views-cache cache/di-cache.php
exec-in-container app vendor/bin/codecept run "$@"

echo "Running JS tests"
run-in-container client 'yarn && yarn lint && yarn test'

echo "Running chat tests"
run-in-container chat 'yarn && yarn lint && yarn test'

echo "Done!"
