#!/bin/bash

export FS_ENV=test

set -e

. $(dirname "$0")/inc.sh

echo "Running npm install"
chat-npm-install

echo "Bring up containers"
dc up --build -d

echo "Waiting for mysql to start"
wait-for-mysql

echo "Initializing database"
sql-query mysql 'drop database if exists foodsharing'
sql-query mysql 'create database foodsharing'
sql-file foodsharing migrations/initial.sql
sql-file foodsharing migrations/static.sql
sql-file foodsharing migrations/27-profilchange.sql
sql-file foodsharing migrations/27-verify.sql
sql-file foodsharing tests/seed.sql
for f in migrations/incremental-*; do
  sql-file foodsharing $f
done

echo "Running composer install"
exec-in-container app composer install

echo "Running tests"
exec-in-container selenium "find /home/seluser/Downloads -type f -print0 | xargs -r -n 1 -0 rm"
exec-in-container app vendor/bin/codecept run "$@"

echo "Running chat tests"
run-in-container chat npm test

echo "Done!"
