#!/bin/bash

export FS_ENV=test

set -o errexit

dir=$(dirname "$0")

# shellcheck source=./inc.sh
source "$dir"/inc.sh

echo "Running chat tests"
run-in-container chat 'yarn && yarn lint && yarn test'

echo "Done!"

